# Generated by Django 5.2.11 on 2026-02-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='state',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
