# Generated by Django 6.0 on 2026-02-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
