# Generated by Django 6.0 on 2026-02-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donation_otp_donation_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
