# Generated by Django 5.2.9 on 2026-02-06 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donation_otp_donation_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
