# Generated by Django 5.2.9 on 2026-02-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donation_amount_donation_receipt_generated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='receipt_number',
            field=models.CharField(default='OLD-RECEIPT', editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
