# Generated by Django 6.0 on 2026-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='receipt_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
