# Generated by Django 5.2.11 on 2026-02-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donation_otp_created_at'),
        ('core', '0002_donation_otp_fields'),
        ('core', '0002_donation_state'),
        ('core', '0006_merge_20260210_2016'),
    ]

    operations = [
    ]
