# Generated by Django 5.2.11 on 2026-02-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260210_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='state',
            field=models.CharField(default='Kerala', editable=False, max_length=50),
        ),
    ]
